### ISSUE TITLE
Grafana build for arm (since v5.4.3)

### ISSUE THREAD

**Issue by balda** [monitoringartist/grafana-xxl#15]
Grafana changelog for v5.4.3
> Build and publish docker images for armv7 and arm64 #14617, thx @johanneswuerbach

Could you also provide arm build?

**Comment by jangaraj** [comment]
Unfortunately, it is not possible to create multiarch image with Docker hub automated build. I don't think that standalone Docker image per architecture is a good approach. 

Anyway, I'm open for any PR, which will use some online CI (Circle CI, Travis, ...) to build multiarch image. It won't be a trivial task.

**Comment by petemyron** [comment]
Docker registry and hub does support multi architecture images now. AWS has some arm support, too!

**Comment by jangaraj** [comment]
Yes, Docker Hub supports multi arch images for a while. Unfortunately, Docker Hub builds don't. There is required a full pipeline, which will build particular image for each architecture and then combine them into multi arch image + push to Docker Hub.
