### ISSUE TITLE
Could you update it to Grafana 4.1-beta1 for Elasticsearch 5.x support. 

### ISSUE THREAD

**Issue by vichaos** [monitoringartist/grafana-xxl#2]
https://github.com/grafana/grafana/blob/master/CHANGELOG.md

**Enhancements**
Postgres: Add support for Certs for Postgres database #6655
Victorops: Add VictorOps notification integration #6411, thx @ichekrygin
Opsgenie: Add OpsGenie notification integratiion #6687, thx @kylemcc
Singlestat: New aggregation on singlestat panel #6740, thx @dirk-leroux
Cloudwatch: Make it possible to specify access and secret key on the data source config page #6697
Table: Added Hidden Column Style for Table Panel #5677, thx @bmundt
Graph: Shared crosshair option renamed to shared tooltip, shows tooltip on all graphs as you hover over one graph. #1578, #6274
Elasticsearch: Added support for Missing option (bucket) for terms aggregation #4244, thx @shanielh
Elasticsearch: Added support for Elasticsearch 5.x #5740, thx @lpic10
CLI: Make it possible to reset the admin password using the grafana-cli. #5479
Influxdb: Support multiple tags in InfluxDB annotations. #4550, thx @adrianlzt
LDAP: Basic Auth now supports LDAP username and password, #6940, thx @utkarshcmu
LDAP: Now works with Auth Proxy, role and organisation mapping & sync will regularly be performed. #6895, thx @Seuf
Alerting: Adds OK as no data option. #6866
Alert list: Order alerts based on state. #6676
Alerting: Add api endpoint for pausing all alerts. #6589
Panel: Added help text for panels. #4079, thx @utkarshcmu

**Bugfixes**
API: HTTP API for deleting org returning incorrect message for a non-existing org #6679
Dashboard: Posting empty dashboard result in corrupted dashboard #5443
Logging: Fixed logging level confing issue #6978
Notifications: Remove html escaping the email subject. #6905
Influxdb: Fixes broken field dropdown when using template vars as measurement. #6473

**Comment by jangaraj** [comment]
It's already available, please use tag `4.1`. It's still beta, so it's not `latest` image.

https://github.com/monitoringartist/grafana-xxl/tree/4.1
https://hub.docker.com/r/monitoringartist/grafana-xxl/tags/

**Comment by jangaraj** [comment]
4.1 was released yesterday, now it's in `latest` image
