### ISSUE TITLE
[ops request] Can you create a new branch for enterprise edition?

### ISSUE THREAD

**Issue by petemyron** [monitoringartist/grafana-xxl#25]
I'm ready to submit a pull request for Grafana Enterprise, but don't want to create it against master or 6.3 branches. If I make a pull request against master, does github give you the ability to merge to a new branch or do you have to branch first, then make the pull request?

Definitely needs its own branch, unless I add a check for the license key or something similar.

Thoughts?

**Comment by jangaraj** [comment]
How can I download Grafana Enterprise?

**Comment by petemyron** [comment]
Pay Grafana Labs lots of money, log into grafana.com, then get the download link + license keys. It's required to get the premium plugins that you also have to pay lots of money for...

**Comment by petemyron** [comment]
And my pull request will have that link in it, too. Obviously, it's 'worthless' without the license.

**Comment by jangaraj** [comment]
Will it be valuable for OSS community, when it is paid product? Are you allowed to publish download link (I can find any public link)?
Enterprise version is very specific use case. IMHO it won't provide good value for open source community + enterprise shouldn't use 3rd party Docker images. The safest option for enterprise will be to build&manage own enteprise Docker image/repo.

**Comment by petemyron** [comment]
These are great questions. Thanks for your diligence!

The image is available on hub.docker: https://hub.docker.com/r/grafana/grafana-enterprise

I know they have lots of customers paying for the premium version, and I intend to use all plugins, free and premium. I can't believe that I'm the only one.

I guess just let me know if you still don't want to and I'll create a separate repo.

**Comment by jangaraj** [comment]
Unfortunately, this won't be possible. Private plugins can't be part of public Docker image. I recommend to use official enterprise image. There is option to install plugins (`GF_INSTALL_PLUGINS=`), but you need to specify plugins explicitly. Maybe will be good idea to open/implement feature request, which will install all available plugins with `GF_INSTALL_PLUGINS=all`.
