### ISSUE TITLE
Things break with move to 6.3.4

### ISSUE THREAD

**Issue by derwin12** [monitoringartist/grafana-xxl#26]
W: --force-yes is deprecated, use one of the options starting with --allow instead.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   302    0   302    0     0    936      0 --:--:-- --:--:-- --:--:--   934
dpkg-deb: error: '/tmp/grafana.deb' is not a debian format archive
dpkg: error processing archive /tmp/grafana.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/grafana.deb
ERROR: Service 'grafana-xxl' failed to build: The command '/bin/sh -c apt-get update &&   apt-get -y --force-yes --no-install-recommends install libfontconfig curl ca-certificates git jq &&   curl -L ${GRAFANA_DEB_URL} > /tmp/grafana.deb &&   dpkg -i /tmp/grafana.deb &&   rm -f /tmp/grafana.deb &&   curl -L ${GOSU_BIN_URL} > /usr/sbin/gosu &&   chmod +x /usr/sbin/gosu &&   for plugin in $(curl -s https://grafana.net/api/plugins?orderBy=name | jq '.items[] | select(.internal=='false') | .slug' | tr -d '"'); do grafana-cli --pluginsDir "${GF_PLUGIN_DIR}" plugins install $plugin; done &&   sed -i 's#<title>Grafana</title>#<title>Grafana XXL</title>#g' /usr/share/grafana/public/views/index-template.html &&   sed -i 's#<title>Grafana - Error</title>#<title>Grafana XXL - Error</title>#g' /usr/share/grafana/public/views/error-template.html &&   sed -i 's#<div class="logo-wordmark" />#<div class="logo-wordmark"> XXL</div>#g' /usr/share/grafana/public/app/partials/login.html &&   chmod +x /run.sh &&   mkdir -p /usr/share/grafana/.aws/ &&   touch /usr/share/grafana/.aws/credentials &&   apt-get remove -y --allow-downgrades --allow-remove-essential --allow-change-held-packages curl git jq &&   apt-get autoremove -y --allow-downgrades --allow-remove-essential --allow-change-held-packages &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by jangaraj** [comment]
Thanks. Download URL was changed.
