### ISSUE TITLE
ARM version in DockerHUB

### ISSUE THREAD

**Issue by Kawabountou** [monitoringartist/grafana-xxl#31]
Hi,

Could you create the image of your docker in the dockerhub for ARM version.

I would like to use it in a docker-compose, and without this, ils hard to do it, and stay up to date with your work .

Thant you in advance for your great job

**Comment by jangaraj** [comment]
Unfortunately, that can be a lot of work (cross compiling, CI setup, multiarch image, ...) and arm is not just single space: arm/v6,arm/v7,arm64/v8, so it will triple whole effort. I would recommend official Grafana images in this case (they support arm, arm64).
