### ISSUE TITLE
Still old version

### ISSUE THREAD

**Issue by pencakj** [monitoringartist/grafana-xxl#37]
Hello, 

I don't know what I'm doing wrong nut I still get version 6.7.1

Freshly installed system but no 7.2.2

Thanks

**Comment by jangaraj** [comment]
My guess: you have been using `latest` tag. It will be better to use tag explicitly. I have update `latest` to `7.3` recently -  https://hub.docker.com/repository/docker/monitoringartist/grafana-xxl/builds
