### ISSUE TITLE
Grafana-XXL and Zabbix plugin

### ISSUE THREAD

**Issue by gonzalo-** [monitoringartist/grafana-xxl#4]
Hello,

I have been using this container for a while now, and is awesome, but couple days ago, my container stop working, and when I re-created it, the Zabbix plugin is missing, any idea?

The way that I built the container is:

```
docker run -d -v /var/lib/grafana --name grafana-xxl-storage busybox:latest
docker run \
  -d \
  -p 3000:3000 \
  --name=monitoreo \
  -e "GF_SERVER_ROOT_URL=http://grafana.foobar.com" \
  -e "GF_SECURITY_ADMIN_PASSWORD=34812b37189" \
  monitoringartist/grafana-xxl
```

Thanks!

**Comment by jangaraj** [comment]
Plugin is there:
```
docker pull monitoringartist/grafana-xxl && docker run --rm -ti --entrypoint grafana-cli monitoringartist/grafana-xxl plugins ls | grep zabbix
Using default tag: latest
latest: Pulling from monitoringartist/grafana-xxl
Digest: sha256:f49c15ff88caf9d66bc8875dcd91600c2e3ac1b2580cf8c31ac8baf310be82d9
Status: Image is up to date for monitoringartist/grafana-xxl:latest
alexanderzobnin-zabbix-app @ 3.3.0
```

Probably you have lost your plugins configuration = your old `grafana-xxl-storage` container has been removed/.... You need to configure your Grafana instance again (datasources, dashboards, ...).

**Comment by gonzalo-** [comment]
Thank you, for the quick response, I have the same:

```
docker run --rm -ti --entrypoint grafana-cli monitoringartist/grafana-xxl plugins ls | grep zabbix
alexanderzobnin-zabbix-app @ 3.3.0
```

The problem seems to be on the Dashboard, the plugin doesn't appear.

**Comment by jangaraj** [comment]
You have to enable it first. Please use Zabbix plugin doc http://docs.grafana-zabbix.org/installation/configuration/

**Comment by gonzalo-** [comment]
yes, I understand, but is not there.

**Comment by jangaraj** [comment]
Check container logs.

**Comment by gonzalo-** [comment]
Something like this?

```
# docker container logs --tail 3000 38ef0dbadfc1 | grep zabbi
Updating alexanderzobnin-zabbix-app 
Removing plugin: alexanderzobnin-zabbix-app
Error: ✗ remove /grafana-plugins/alexanderzobnin-zabbix-app/.github: directory not empty
```

**Comment by jangaraj** [comment]
Yes, you have some problem with autoupdate. Use `-e UPGRADEALL=false` to disable autopdate or solve your problem - probably it a problem of used storage driver. Definitely it's not a problem of the image, but your configuration. For the record, I don't have that problem:
```
Updating alexanderzobnin-zabbix-app
Removing plugin: alexanderzobnin-zabbix-app
installing alexanderzobnin-zabbix-app @ 3.4.0
from url: https://grafana.net/api/plugins/alexanderzobnin-zabbix-app/versions/3.4.0/download
into: /grafana-plugins
```

**Comment by gonzalo-** [comment]
Thank you!
